---
- hosts: {$HOST.GROUP}
  remote_user: {$USER}
  become: True
  
  vars:
    zabbix_server: "{ZABBIX_SERVER_IP}"

  tasks:
  - name: Installing the Zabbix Agent
    apt:
      name: zabbix-agent
      state: present

  - name: Creates directory for custom scripts
    file:
      path: /etc/zabbix/scripts/
      state: directory
      owner: zabbix
      group: zabbix
      mode: '0755'

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^LogFileSize=0'
      line: 'LogFileSize=256'
      backrefs: yes

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# EnableRemoteCommands=0'
      line: 'EnableRemoteCommands=1'
      backrefs: yes

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server=127.0.0.1'
      line: 'Server={{ zabbix_server }}'
      backrefs: yes

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^ServerActive=127.0.0.1'
      line: 'ServerActive={{ zabbix_server }}'
      backrefs: yes

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Hostname=Zabbix server'
      line: 'Hostname={{ ansible_hostname }}'
      backrefs: yes

  - lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^# Timeout=3'
      line: 'Timeout=3'
      backrefs: yes

  - name: Starting the Zabbix Agent
    service: name=zabbix-agent state=started enabled=yes
